// frontend/src/components/charts/BarChartCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useThemeStore } from '@/stores/theme'
import { formatCurrency, formatCompactNumber } from '@/utils/format'

interface DataPoint {
  name: string
  value: number
  [key: string]: number | string
}

const props = withDefaults(defineProps<{
  title: string
  data: DataPoint[]
  dataKey?: string
  xAxisKey?: string
  color?: string
  colors?: string[]
  showGrid?: boolean
  horizontal?: boolean
  height?: number
  formatYAxis?: 'currency' | 'number' | 'compact'
  showLabels?: boolean
}>(), {
  dataKey: 'value',
  xAxisKey: 'name',
  color: '#60a5fa',
  showGrid: true,
  horizontal: false,
  height: 300,
  formatYAxis: 'compact',
  showLabels: true,
})

const themeStore = useThemeStore()

const formatValue = (value: number) => {
  switch (props.formatYAxis) {
    case 'currency':
      return formatCurrency(value)
    case 'compact':
      return formatCompactNumber(value)
    default:
      return value.toLocaleString('pt-BR')
  }
}

const series = computed(() => [{
  name: props.title,
  data: props.data.map(item => item[props.dataKey] as number)
}])

const chartOptions = computed(() => ({
  chart: {
    type: props.horizontal ? 'bar' : 'bar',
    toolbar: { show: false },
    background: 'transparent',
  },
  plotOptions: {
    bar: {
      horizontal: props.horizontal,
      borderRadius: 4,
      columnWidth: '60%',
      dataLabels: {
        position: props.horizontal ? 'right' : 'top',
      },
    },
  },
  colors: props.colors || [props.color],
  dataLabels: {
    enabled: props.showLabels,
    formatter: (val: number) => formatValue(val),
    style: {
      fontSize: '11px',
      colors: ['#94a3b8'],
    },
    offsetY: props.horizontal ? 0 : -20,
  },
  grid: {
    show: props.showGrid,
    borderColor: themeStore.theme === 'dark' ? '#334155' : '#e2e8f0',
    strokeDashArray: 3,
  },
  xaxis: {
    categories: props.data.map(item => item[props.xAxisKey]),
    labels: {
      style: {
        colors: themeStore.theme === 'dark' ? '#64748b' : '#475569',
        fontSize: '11px',
      },
      rotate: props.horizontal ? 0 : -45,
    },
    axisBorder: { show: false },
    axisTicks: { show: false },
  },
  yaxis: {
    labels: {
      style: {
        colors: themeStore.theme === 'dark' ? '#64748b' : '#475569',
        fontSize: '12px',
      },
      formatter: (val: number) => formatValue(val),
    },
  },
  tooltip: {
    theme: themeStore.theme,
    y: {
      formatter: (val: number) => formatValue(val),
    },
  },
  theme: {
    mode: themeStore.theme,
  },
}))
</script>

<template>
  <div class="card">
    <h3 class="card-header">{{ title }}</h3>
    <apexchart
      type="bar"
      :height="height"
      :options="chartOptions"
      :series="series"
    />
  </div>
</template>

// frontend/src/components/charts/BarChartCard.tsx
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Cell,
  LabelList,
} from 'recharts';
import { formatCurrency, formatCompactNumber } from '../../utils/format';

interface DataPoint {
  name: string;
  value: number;
  [key: string]: number | string;
}

interface BarChartCardProps {
  title: string;
  data: DataPoint[];
  dataKey?: string;
  xAxisKey?: string;
  color?: string;
  colors?: string[];
  showGrid?: boolean;
  horizontal?: boolean;
  height?: number;
  formatYAxis?: 'currency' | 'number' | 'compact';
  showLabels?: boolean;
}

export function BarChartCard({
  title,
  data,
  dataKey = 'value',
  xAxisKey = 'name',
  color = '#60a5fa',
  colors,
  showGrid = true,
  horizontal = false,
  height = 300,
  formatYAxis = 'compact',
  showLabels = true,
}: BarChartCardProps) {
  const formatValue = (value: number) => {
    switch (formatYAxis) {
      case 'currency':
        return formatCurrency(value);
      case 'compact':
        return formatCompactNumber(value);
      default:
        return value.toLocaleString('pt-BR');
    }
  };

  return (
    <div className="card">
      <h3 className="card-header">{title}</h3>
      <ResponsiveContainer width="100%" height={height}>
        <BarChart
          data={data}
          layout={horizontal ? 'vertical' : 'horizontal'}
          margin={{ top: 20, right: 30, left: 60, bottom: 60 }}
        >
          {showGrid && (
            <CartesianGrid
              strokeDasharray="3 3"
              stroke="#334155"
              vertical={!horizontal}
              horizontal={horizontal}
            />
          )}
          {horizontal ? (
            <>
              <XAxis
                type="number"
                stroke="#64748b"
                fontSize={12}
                tickLine={false}
                axisLine={false}
                tickFormatter={formatValue}
              />
              <YAxis
                type="category"
                dataKey={xAxisKey}
                stroke="#64748b"
                fontSize={11}
                tickLine={false}
                axisLine={false}
                width={120}
              />
            </>
          ) : (
            <>
              <XAxis
                dataKey={xAxisKey}
                stroke="#64748b"
                fontSize={11}
                tickLine={false}
                axisLine={false}
                angle={-45}
                textAnchor="end"
                height={80}
              />
              <YAxis
                stroke="#64748b"
                fontSize={12}
                tickLine={false}
                axisLine={false}
                tickFormatter={formatValue}
              />
            </>
          )}
          <Tooltip
            contentStyle={{
              backgroundColor: '#1e293b',
              border: '1px solid #334155',
              borderRadius: '8px',
              color: '#f1f5f9',
            }}
            formatter={(value: number) => [formatValue(value), '']}
          />
          <Bar
            dataKey={dataKey}
            fill={color}
            radius={[4, 4, 0, 0]}
            maxBarSize={60}
          >
            {colors && data.map((_, index) => (
              <Cell key={`cell-${index}`} fill={colors[index % colors.length]} />
            ))}
            {showLabels && (
              <LabelList
                dataKey={dataKey}
                position={horizontal ? 'right' : 'top'}
                formatter={formatValue}
                fill="#94a3b8"
                fontSize={11}
              />
            )}
          </Bar>
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
}
