// frontend/src/components/charts/LineChartCard.tsx
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from 'recharts';
import { formatCurrency, formatCompactNumber } from '../../utils/format';

interface DataPoint {
  name: string;
  [key: string]: number | string;
}

interface LineChartCardProps {
  title: string;
  data: DataPoint[];
  dataKeys: Array<{
    key: string;
    color: string;
    name: string;
    type?: 'monotone' | 'linear' | 'step';
  }>;
  xAxisKey?: string;
  showGrid?: boolean;
  showLegend?: boolean;
  height?: number;
  formatYAxis?: 'currency' | 'number' | 'compact';
}

export function LineChartCard({
  title,
  data,
  dataKeys,
  xAxisKey = 'name',
  showGrid = true,
  showLegend = true,
  height = 300,
  formatYAxis = 'compact',
}: LineChartCardProps) {
  const formatValue = (value: number) => {
    switch (formatYAxis) {
      case 'currency':
        return formatCurrency(value);
      case 'compact':
        return formatCompactNumber(value);
      default:
        return value.toLocaleString('pt-BR');
    }
  };

  return (
    <div className="card">
      <h3 className="card-header">{title}</h3>
      <ResponsiveContainer width="100%" height={height}>
        <LineChart data={data} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
          {showGrid && (
            <CartesianGrid
              strokeDasharray="3 3"
              stroke="#334155"
              vertical={false}
            />
          )}
          <XAxis
            dataKey={xAxisKey}
            stroke="#64748b"
            fontSize={12}
            tickLine={false}
            axisLine={false}
          />
          <YAxis
            stroke="#64748b"
            fontSize={12}
            tickLine={false}
            axisLine={false}
            tickFormatter={formatValue}
          />
          <Tooltip
            contentStyle={{
              backgroundColor: '#1e293b',
              border: '1px solid #334155',
              borderRadius: '8px',
              color: '#f1f5f9',
            }}
            formatter={(value: number) => [formatValue(value), '']}
          />
          {showLegend && (
            <Legend
              wrapperStyle={{ paddingTop: '20px' }}
              iconType="circle"
              iconSize={8}
            />
          )}
          {dataKeys.map((dk) => (
            <Line
              key={dk.key}
              type={dk.type || 'monotone'}
              dataKey={dk.key}
              name={dk.name}
              stroke={dk.color}
              strokeWidth={2}
              dot={{ fill: dk.color, strokeWidth: 0, r: 4 }}
              activeDot={{ r: 6, strokeWidth: 0 }}
            />
          ))}
        </LineChart>
      </ResponsiveContainer>
    </div>
  );
}

// frontend/src/components/charts/LineChartCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useThemeStore } from '@/stores/theme'
import { formatCurrency, formatCompactNumber } from '@/utils/format'

interface DataKey {
  key: string
  color: string
  name: string
  type?: 'line' | 'area'
}

interface DataPoint {
  name: string
  [key: string]: number | string
}

const props = withDefaults(defineProps<{
  title: string
  data: DataPoint[]
  dataKeys: DataKey[]
  height?: number
  formatYAxis?: 'currency' | 'number' | 'compact'
  showGrid?: boolean
}>(), {
  height: 300,
  formatYAxis: 'compact',
  showGrid: true,
})

const themeStore = useThemeStore()

const formatValue = (value: number) => {
  switch (props.formatYAxis) {
    case 'currency':
      return formatCurrency(value)
    case 'compact':
      return formatCompactNumber(value)
    default:
      return value.toLocaleString('pt-BR')
  }
}

const series = computed(() =>
  props.dataKeys.map(dk => ({
    name: dk.name,
    data: props.data.map(item => item[dk.key] as number),
  }))
)

const chartOptions = computed(() => ({
  chart: {
    type: 'line',
    toolbar: { show: false },
    background: 'transparent',
  },
  colors: props.dataKeys.map(dk => dk.color),
  stroke: {
    curve: 'smooth',
    width: 2,
  },
  grid: {
    show: props.showGrid,
    borderColor: themeStore.theme === 'dark' ? '#334155' : '#e2e8f0',
    strokeDashArray: 3,
  },
  xaxis: {
    categories: props.data.map(item => item.name),
    labels: {
      style: {
        colors: themeStore.theme === 'dark' ? '#64748b' : '#475569',
        fontSize: '11px',
      },
    },
    axisBorder: { show: false },
    axisTicks: { show: false },
  },
  yaxis: {
    labels: {
      style: {
        colors: themeStore.theme === 'dark' ? '#64748b' : '#475569',
        fontSize: '12px',
      },
      formatter: (val: number) => formatValue(val),
    },
  },
  tooltip: {
    theme: themeStore.theme,
    y: {
      formatter: (val: number) => formatValue(val),
    },
  },
  legend: {
    position: 'top',
    horizontalAlign: 'right',
    labels: {
      colors: themeStore.theme === 'dark' ? '#94a3b8' : '#475569',
    },
  },
  theme: {
    mode: themeStore.theme,
  },
}))
</script>

<template>
  <div class="card">
    <h3 class="card-header">{{ title }}</h3>
    <apexchart
      type="line"
      :height="height"
      :options="chartOptions"
      :series="series"
    />
  </div>
</template>
