// frontend/src/pages/AtendimentoPage.vue
<script setup lang="ts">
import { computed } from 'vue'
import { storeToRefs } from 'pinia'
import { useDashboardStore } from '@/stores/dashboard'
import FilterBar from '@/components/filters/FilterBar.vue'
import TabNavigation from '@/components/navigation/TabNavigation.vue'
import DataTable from '@/components/dashboard/DataTable.vue'
import BarChartCard from '@/components/charts/BarChartCard.vue'
import RevalidatingIndicator from '@/components/ui/RevalidatingIndicator.vue'
import PageSkeleton from '@/components/ui/PageSkeleton.vue'
import { DollarSign, Users, TrendingUp, Award } from 'lucide-vue-next'
import { formatCurrency } from '@/utils/format'

const store = useDashboardStore()
const { data, loadingStates, revalidatingStates, filters, filterOptions } = storeToRefs(store)

const isLoading = computed(() => loadingStates.value.atendimento)
const isRevalidating = computed(() => revalidatingStates.value.atendimento)

const atendimentoData = computed(() => data.value.atendimento)

// Colunas para tabela de desempenho
const desempenhoColumns = [
  { key: 'responsavel', header: 'Responsável' },
  { key: 'totalOrcamentos', header: 'Orçamentos' },
  { key: 'valorTotalOrcado', header: 'Valor Orçado', render: (val: number) => formatCurrency(val) },
  { key: 'aprovados', header: 'Aprovados' },
  { key: 'valorTotalAprovado', header: 'Valor Aprovado', render: (val: number) => formatCurrency(val) },
  { key: 'percentual', header: '% Aprovação', render: (val: number) => `${val.toFixed(1)}%` },
]

// Colunas para tabela de ticket médio
const ticketColumns = [
  { key: 'procedimento', header: 'Procedimento' },
  { key: 'vendas', header: 'Vendas' },
  { key: 'ticketMedio', header: 'Ticket Médio', render: (val: number) => formatCurrency(val) },
  { key: 'faturamentoTotal', header: 'Faturamento', render: (val: number) => formatCurrency(val) },
]

// Dados para gráfico Pareto
const paretoChartData = computed(() => {
  if (!atendimentoData.value?.pareto8020) return []
  return atendimentoData.value.pareto8020.slice(0, 10).map((item) => ({
    name: item.procedimento.length > 20 ? item.procedimento.substring(0, 20) + '...' : item.procedimento,
    value: item.faturamentoTotal,
  }))
})

// Totais calculados
const totalOrcamentos = computed(() => {
  if (!atendimentoData.value?.desempenho) return 0
  return atendimentoData.value.desempenho.reduce((acc, item) => acc + item.totalOrcamentos, 0)
})

const totalAprovados = computed(() => {
  if (!atendimentoData.value?.desempenho) return 0
  return atendimentoData.value.desempenho.reduce((acc, item) => acc + item.aprovados, 0)
})

const taxaAprovacaoGeral = computed(() => {
  if (totalOrcamentos.value === 0) return 0
  return (totalAprovados.value / totalOrcamentos.value) * 100
})

function handleFilterChange(newFilters: typeof filters.value) {
  store.setFilters(newFilters)
  store.refetch()
}
</script>

<template>
  <div class="space-y-6">
    <TabNavigation />

    <div class="flex items-center justify-between gap-4">
      <div class="flex-1">
        <FilterBar
          :filters="filters"
          :filter-options="filterOptions"
          @update:filters="handleFilterChange"
        />
      </div>
      <RevalidatingIndicator :is-revalidating="isRevalidating" />
    </div>

    <PageSkeleton v-if="isLoading && !atendimentoData" />

    <template v-else>
      <!-- KPIs -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div class="card p-5">
          <div class="flex items-center gap-3 mb-3">
            <div class="p-2 bg-green-500/20 rounded-lg">
              <DollarSign class="w-5 h-5 text-green-500" />
            </div>
            <span class="text-sm text-[var(--color-text-muted)]">Total Faturamento</span>
          </div>
          <p class="text-2xl font-bold text-[var(--color-text-primary)]">
            {{ atendimentoData?.totalFaturamentoFormatado || formatCurrency(atendimentoData?.totalFaturamento || 0) }}
          </p>
        </div>

        <div class="card p-5">
          <div class="flex items-center gap-3 mb-3">
            <div class="p-2 bg-blue-500/20 rounded-lg">
              <Users class="w-5 h-5 text-blue-500" />
            </div>
            <span class="text-sm text-[var(--color-text-muted)]">Total Orçamentos</span>
          </div>
          <p class="text-2xl font-bold text-[var(--color-text-primary)]">
            {{ totalOrcamentos.toLocaleString('pt-BR') }}
          </p>
        </div>

        <div class="card p-5">
          <div class="flex items-center gap-3 mb-3">
            <div class="p-2 bg-purple-500/20 rounded-lg">
              <TrendingUp class="w-5 h-5 text-purple-500" />
            </div>
            <span class="text-sm text-[var(--color-text-muted)]">Aprovados</span>
          </div>
          <p class="text-2xl font-bold text-[var(--color-text-primary)]">
            {{ totalAprovados.toLocaleString('pt-BR') }}
          </p>
        </div>

        <div class="card p-5">
          <div class="flex items-center gap-3 mb-3">
            <div class="p-2 bg-yellow-500/20 rounded-lg">
              <Award class="w-5 h-5 text-yellow-500" />
            </div>
            <span class="text-sm text-[var(--color-text-muted)]">Taxa de Aprovação</span>
          </div>
          <p class="text-2xl font-bold text-[var(--color-text-primary)]">
            {{ taxaAprovacaoGeral.toFixed(1) }}%
          </p>
        </div>
      </div>

      <!-- Tabela de Desempenho -->
      <div class="card p-6">
        <h3 class="text-lg font-semibold text-[var(--color-text-primary)] mb-4">
          Desempenho por Responsável
        </h3>
        <DataTable
          :columns="desempenhoColumns"
          :data="atendimentoData?.desempenho || []"
          :max-rows="10"
          empty-message="Nenhum dado de desempenho disponível"
        />
      </div>

      <!-- Ticket Médio e Pareto -->
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div class="card p-6">
          <h3 class="text-lg font-semibold text-[var(--color-text-primary)] mb-4">
            Ticket Médio por Procedimento
          </h3>
          <DataTable
            :columns="ticketColumns"
            :data="atendimentoData?.ticketMedioPorProcedimento || []"
            :max-rows="10"
            empty-message="Nenhum dado de ticket médio disponível"
          />
        </div>

        <BarChartCard
          v-if="paretoChartData.length > 0"
          title="Top 10 Procedimentos (Pareto 80/20)"
          :data="paretoChartData"
          color="#8b5cf6"
          format-y-axis="currency"
          :height="350"
          horizontal
        />
      </div>

      <!-- Tabela Pareto Detalhada -->
      <div v-if="atendimentoData?.pareto8020?.length" class="card p-6">
        <h3 class="text-lg font-semibold text-[var(--color-text-primary)] mb-4">
          Análise Pareto 80/20 - Procedimentos
        </h3>
        <div class="overflow-x-auto">
          <table class="w-full text-sm">
            <thead>
              <tr class="border-b border-[var(--color-border-primary)]">
                <th class="text-left py-3 px-4 text-[var(--color-text-muted)] font-medium">Procedimento</th>
                <th class="text-right py-3 px-4 text-[var(--color-text-muted)] font-medium">Ticket Médio</th>
                <th class="text-right py-3 px-4 text-[var(--color-text-muted)] font-medium">Faturamento</th>
                <th class="text-right py-3 px-4 text-[var(--color-text-muted)] font-medium">% Acumulado</th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="(item, index) in atendimentoData.pareto8020.slice(0, 15)"
                :key="index"
                class="border-b border-[var(--color-border-subtle)] hover:bg-[var(--color-bg-tertiary)]"
              >
                <td class="py-3 px-4 text-[var(--color-text-primary)]">{{ item.procedimento }}</td>
                <td class="py-3 px-4 text-right text-[var(--color-text-secondary)]">{{ formatCurrency(item.ticketMedio) }}</td>
                <td class="py-3 px-4 text-right text-[var(--color-text-primary)] font-medium">{{ formatCurrency(item.faturamentoTotal) }}</td>
                <td class="py-3 px-4 text-right">
                  <span
                    :class="[
                      'px-2 py-1 rounded text-xs font-medium',
                      parseFloat(item.percentualAcumulado) <= 80
                        ? 'bg-green-500/20 text-green-500'
                        : 'bg-yellow-500/20 text-yellow-500'
                    ]"
                  >
                    {{ item.percentualAcumulado }}
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </template>
  </div>
</template>

// frontend/src/pages/AtendimentoPage.tsx
import { FilterBar } from '../components/filters/FilterBar';
import { DataTable } from '../components/dashboard/DataTable';
import { PieChartCard } from '../components/charts/PieChartCard';
import { TabNavigation } from '../components/navigation/TabNavigation';
import { useDashboard } from '../hooks/useDashboard';
import { formatCurrency } from '../utils/format';
import { PageSkeleton, RevalidatingIndicator } from '../components/ui/Skeleton';

// Mock data
const mockDesempenho = [
  { responsavel: 'Mayara Rubia', total_orcamentos: 53, valor_total_orcado: 234424.00, aprovados: 52, valor_total_aprovado: 226424.00, percentual: 98 },
  { responsavel: 'Suyane Cristhini', total_orcamentos: 201, valor_total_orcado: 644425.70, aprovados: 200, valor_total_aprovado: 642845.70, percentual: 100 },
];

const mockTicketMedio = [
  { procedimento: 'Voucher', ticket_medio: 1341.95, vendas: 40, faturamento_total: 53678.00 },
  { procedimento: 'MOUNJARO', ticket_medio: 15333.33, vendas: 3, faturamento_total: 46000.00 },
  { procedimento: 'ONDA COOLWAVES', ticket_medio: 5325.00, vendas: 6, faturamento_total: 31950.00 },
  { procedimento: 'MASSAGEM RELAXANTE', ticket_medio: 242.33, vendas: 114, faturamento_total: 27626.00 },
  { procedimento: 'Ultraformer - Boom de colágeno - Face e Pescoço - 3 sessões', ticket_medio: 9000.00, vendas: 3, faturamento_total: 27000.00 },
  { procedimento: 'Ácido Hialurônico - 1 ampola', ticket_medio: 6200.00, vendas: 4, faturamento_total: 24800.00 },
  { procedimento: 'Ultraformer MPT - Face e pescoço', ticket_medio: 7366.67, vendas: 3, faturamento_total: 22100.00 },
  { procedimento: 'VOLNEWMER', ticket_medio: 10665.00, vendas: 2, faturamento_total: 21330.00 },
  { procedimento: 'CONSULTA', ticket_medio: 1037.50, vendas: 20, faturamento_total: 20750.00 },
  { procedimento: 'PROTOCOLO CLARIFY - PICOSURE + FOTONA', ticket_medio: 15000.00, vendas: 1, faturamento_total: 15000.00 },
];

const mockPareto8020 = [
  { name: 'VOLNEWMER', value: 21330.00 },
  { name: 'Voucher', value: 53678.00 },
  { name: 'Ultraformer MPT', value: 22100.00 },
  { name: 'Ácido Hialurônico', value: 24800.00 },
  { name: 'MOUNJARO', value: 46000.00 },
  { name: 'Botox face', value: 18500.00 },
  { name: 'ONDA COOLWAVES', value: 31950.00 },
  { name: 'VOLFORMER', value: 15000.00 },
  { name: 'Botox face e pescoço', value: 12000.00 },
  { name: 'EMFACE - 4 sessões', value: 11000.00 },
];

export function AtendimentoPage() {
  const { data, loadingStates, revalidatingStates, filters, setFilters, filterOptions } = useDashboard();

  // Use specific loading state for atendimento
  const isLoading = loadingStates.atendimento;
  const isRevalidating = revalidatingStates.atendimento;


  const desempenhoColumns = [
    { key: 'responsavel', header: 'Responsável', className: 'text-primary-400' },
    { key: 'total_orcamentos', header: 'Total de Orçamentos', className: 'text-primary-400 text-center', headerClassName: 'text-center' },
    { key: 'valor_total_orcado', header: 'Valor Orçado (R$)', render: (v: string | number) => formatCurrency(Number(v)), className: 'text-primary-400 text-right', headerClassName: 'text-right' },
    { key: 'aprovados', header: 'Aprovados', className: 'text-primary-400 text-center', headerClassName: 'text-center' },
    { key: 'valor_total_aprovado', header: 'Valor Aprovado (R$)', render: (v: string | number) => formatCurrency(Number(v)), className: 'text-primary-400 text-right', headerClassName: 'text-right' },
    {
      key: 'percentual',
      header: '%',
      headerClassName: 'text-center',
      className: 'text-center',
      render: (v: string | number) => (
        <div className="flex items-center justify-center gap-2">
          <span>{v}%</span>
          <div className="w-20 h-2 bg-dark-border rounded-full overflow-hidden">
            <div
              className="h-full bg-primary-500 rounded-full"
              style={{ width: `${v}%` }}
            />
          </div>
        </div>
      ),
    },
  ];

  const ticketMedioColumns = [
    { key: 'procedimento', header: 'Procedimento', className: 'text-primary-400' },
    { key: 'ticket_medio', header: 'Ticket Médio (R$)', render: (v: string | number) => formatCurrency(Number(v)), className: 'text-primary-400 text-right', headerClassName: 'text-right' },
    { key: 'vendas', header: 'Vendas', className: 'text-primary-400 text-center', headerClassName: 'text-center' },
    { key: 'faturamento_total', header: 'Faturamento Total (R$)', render: (v: string | number) => formatCurrency(Number(v)), className: 'text-primary-400 text-right', headerClassName: 'text-right' },
  ];

  // Mostra skeleton enquanto carrega e não tem dados
  if (isLoading && !data.atendimento) {
    return (
      <div className="space-y-6">
        <TabNavigation />
        <FilterBar
          filters={filters}
          onFilterChange={setFilters}
          filterOptions={filterOptions}
          showProfissional
        />
        <PageSkeleton />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Tabs - Navigation */}
      <TabNavigation />

      {/* Filters with revalidating indicator */}
      <div className="flex items-center justify-between gap-4">
        <div className="flex-1">
          <FilterBar
            filters={filters}
            onFilterChange={setFilters}
            filterOptions={filterOptions}
            showProfissional
          />
        </div>
        <RevalidatingIndicator isRevalidating={isRevalidating} />
      </div>

      {/* Desempenho Table */}
      <DataTable
        title="Desempenho"
        columns={desempenhoColumns}
        data={mockDesempenho}
      />

      {/* Ticket Médio por Procedimento Section */}
      <h2 className="text-lg font-semibold text-dark-text mt-8">TICKED MÉDIO POR PROCEDIMENTO</h2>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Ticket Médio Table */}
        <DataTable
          title="Ticked Medio por Procedimento"
          columns={ticketMedioColumns}
          data={mockTicketMedio}
        />

        {/* Pareto 80/20 Pie Chart */}
        <PieChartCard
          title="Ticked Medio por Procedimento 80/20"
          data={mockPareto8020}
          showTotal
          totalLabel=""
          height={400}
          innerRadius={80}
          outerRadius={140}
        />
      </div>

    </div>
  );
}
